import LCD as _lcd
import Imaging as imaging
import Camera as camera
import Analysis as analysis



if __name__ == '__main__':


    #    1. SET UP

    #Set up Camera
    cam = imaging.Camera()
    cam.configureGPIO()
    cam.configureProperties()

    #Setup LCD
    lcd = _lcd.Lcd()


    #    2. IMAGING

    #Begin the Imaging Sequence
    #Normalize Exposure and Spatial values
    images = imaging.Imaging()
    images.acquireImages(cam)
    image_masks = images.normalizeSpatial()

    #Apply mask generated by normalization
    masked_image = images.maskImage(image_masks)

    """
    Taking multiple images and masking them still needs to be added
    """

    #    3. Analysis

    #Calculate stats and plot
    stats = analysis.Analysis(masked_image)
    stats.findMax()
    stats.calcStats()
    stats.generatePlots()


    #   4. Cleanup
    cam.cleanUp()